feat: add shop page
dafundacom/gamedaim.com pull request #160
Opened 2023-06-17 10:39 UTC by beruangdev

2023-06-17 11:02 UTC, karyanayandi approved these changes

2023-06-17 11:02 UTC, karyanayandi commented on packages/web/src/components/Banner/BannerShop.tsx
> +      "justify-center content-center bg-[#F39C12] hover:bg-theme-800 hover:text-white p-2 cursor-pointer border-none ring-0 absolute rounded-full top-[48%]"
pake text-background, hover:bg-primary

2023-06-17 11:02 UTC, karyanayandi commented on packages/web/src/components/Banner/BannerTopup.tsx
> +            className="breadcrumb-topup dark:text-theme-200 text-white"
pake text-foreground/opacity value

2023-06-17 11:02 UTC, karyanayandi commented on packages/web/src/components/Banner/BannerTopup.tsx
> +              <MdChevronRight aria-label="Breadcrumb" className="text-white" />
text-background

2023-06-17 11:02 UTC, karyanayandi commented on packages/web/src/components/Banner/BannerTopup.tsx
> +              <BreadcrumbLink className="text-[40px] text-white" href={url}>
sama text-background

2023-06-17 11:02 UTC, karyanayandi commented on packages/web/src/components/Card/ShopCard.tsx
> +"use client"
tambah jarak

2023-06-17 11:02 UTC, karyanayandi commented on packages/web/src/components/Navigation/TopNav.tsx
> +        className="opacity-1 dark:bg-theme-900 fixed left-auto top-0 z-[49] -my-0 mx-auto box-border flex h-16 w-full items-center border-none bg-white px-2 py-0 align-baseline shadow-lg outline-none
pake bg-background/<opacity-value>. begitu juga untuk bg dan text. ga perlu tambah style untuk variant dark karena udah otomatis di css.

2023-06-17 11:22 UTC, beruangdev commented on packages/web/src/components/Banner/BannerTopup.tsx
> +            className="breadcrumb-topup dark:text-theme-200 text-white"
opacitynya berapa yan?

2023-06-18 05:39 UTC, karyanayandi requested changes

2023-06-18 05:39 UTC, karyanayandi commented on packages/server/src/modules/top-up/top-up.route.ts
> +    "/digiflazz/price-list-prepaid/data",
hapus karena ga dipake

2023-06-18 05:39 UTC, karyanayandi commented on packages/web/src/components/List/ListLinkTopup.tsx
> +            className="dark:border-theme-600 border-theme-300 h-[unset] rounded-lg focus:ring-0"
ganti border-border

2023-06-18 05:39 UTC, karyanayandi commented on packages/web/src/components/Picture/NextPicture.tsx
> +            className={"bg-theme-300 dark:text-theme-900 h-full w-full"}
ganti bg-background/<opacity-value>

2023-06-18 05:39 UTC, karyanayandi commented on packages/web/src/app/[locale]/(auth)/auth/forgot-password/form.tsx
> +            className="text-muted border-muted bg-muted my-8 flex rounded-lg border border-blue-300 bg-blue-50 p-4 text-sm text-blue-800"
ganti border-primary atau border-info

2023-06-18 05:39 UTC, karyanayandi commented on packages/web/src/app/[locale]/(auth)/auth/forgot-password/form.tsx
> +            className="text-muted border-muted bg-muted my-8 flex rounded-lg border border-blue-300 bg-blue-50 p-4 text-sm text-blue-800"
text dan bg nya juga

2023-06-18 05:39 UTC, karyanayandi commented on packages/web/src/app/[locale]/(auth)/auth/login/form.tsx
> +            className="border-muted bg-muted text-muted inline-flex items-center justify-center rounded-lg border border-gray-200 bg-white px-5 py-3 text-center text-sm font-medium text-gray-900 hove
ini juga pake warna yang ada di tailwind config

2023-06-18 05:39 UTC, karyanayandi commented on packages/web/src/app/[locale]/(auth)/auth/login/form.tsx
> +            className="border-muted bg-muted text-muted inline-flex items-center justify-center rounded-lg border border-gray-200 bg-white px-5 py-3 text-center text-sm font-medium text-gray-900 hove
ini juga pake warna yang ada di tailwind config

2023-06-18 10:50 UTC, closed without merging