feat: tambah comment di top-up
dafundacom/gamedaim.com pull request #197
Opened 2023-06-30 16:10 UTC by beruangdev

2023-07-01 04:18 UTC, karyanayandi requested changes

2023-07-01 04:18 UTC, karyanayandi commented on packages/web/src/components/Banner/BannerTopup.tsx
> +    console.log("🚀 ~ file: BannerTopup.tsx:19 ~ props:", props)
delete

2023-07-01 04:53 UTC, ghizzkira requested changes

2023-07-01 04:53 UTC, ghizzkira commented on packages/web/src/components/Card/ShopCard.tsx
> +      React.useState<number>(0)
Biarkan nilai awal undefined agar tidak tampilkan bila nilai nya nol

2023-07-01 04:53 UTC, ghizzkira commented on packages/web/src/components/PaymentMethod/PaymentMethod.tsx
Hapus file sudah ada di folder Form

2023-07-01 04:53 UTC, ghizzkira commented on packages/web/src/components/PaymentMethod/index.ts
Hapus

2023-07-01 04:53 UTC, ghizzkira commented on packages/web/src/components/Picture/CoverTopUp.tsx
Hapus file sudah ada di folder Image

2023-07-01 04:53 UTC, ghizzkira commented on packages/web/src/components/Picture/IconTopUp.tsx
Hapus file sudah ada di folder Image

2023-07-01 04:53 UTC, ghizzkira commented on packages/web/src/components/Picture/InfoIdTopUp.tsx
Hapus file sudah ada di folder Image

2023-07-01 04:53 UTC, ghizzkira commented on packages/web/src/components/Picture/NextPicture.tsx
Hapus file sudah ada di folder Image (Image.tsx)

2023-07-01 04:53 UTC, ghizzkira commented on packages/web/src/components/Picture/ThumbnailTopUp.tsx
Hapus file sudah ada di folder Image

2023-07-01 04:53 UTC, ghizzkira commented on packages/web/src/components/Picture/index.tsx
Hapus file sudah ada di folder Image

2023-07-01 04:53 UTC, ghizzkira commented on packages/web/src/components/UI/Form/AddTopUpServerForm.tsx
Hapus file sudah ada di folder Form

2023-07-01 04:53 UTC, ghizzkira commented on packages/web/src/components/UI/Form/AddVoucherTopUpForm.tsx
Hapus file sudah ada di folder comp../Form

2023-07-01 04:53 UTC, ghizzkira commented on packages/web/src/components/UI/Form/SelectPrice.tsx
Hapus file sudah ada di folder comp../Form

2023-07-02 05:44 UTC, ghizzkira requested changes

2023-07-02 05:44 UTC, ghizzkira commented on packages/web/src/components/UI/Form/TopUpEditableParagraph.tsx
> +import { FaRegTimesCircle } from "react-icons/fa"
Pindahkan Icon ke folder UI/Icon

2023-07-02 05:44 UTC, ghizzkira commented on packages/web/src/components/UI/Form/TopUpEditableParagraph.tsx
> +import { FaRegTimesCircle } from "react-icons/fa"
Pindahkan Icon ke folder UI/Icon

2023-07-02 05:44 UTC, ghizzkira commented on packages/web/src/components/UI/Form/TopUpEditableParagraph.tsx
> +import { FaRegTimesCircle } from "react-icons/fa"
Pindahkan Icon ke folder UI/Icon

2023-07-02 05:44 UTC, ghizzkira commented on packages/web/src/components/UI/Form/TopUpEditableParagraph.tsx
> +import { Textarea } from "../Textarea"
Gunakan absolute import

2023-07-02 05:44 UTC, ghizzkira commented on packages/web/src/components/UI/Form/TopUpCommentForm.tsx
> +import { Icon } from "../Icon"
gunakan absolute import dan urutkan

2023-07-02 10:05 UTC, ghizzkira commented on packages/web/src/utils/get-total-price.ts
Hapus sudah ada di helper

2023-07-02 10:07 UTC, ghizzkira approved these changes

2023-07-02 10:29 UTC, karyanayandi approved these changes

2023-07-02 10:29 UTC, merged