style: top-up-review mobile design
dafundacom/gamedaim.com pull request #700
Opened 2023-05-28 13:16 UTC by beruangdev

2023-05-29 03:45 UTC, karyanayandi requested changes

2023-05-29 03:45 UTC, karyanayandi commented on packages/web/src/components/Form/CommentForm.tsx
> +                    auth?.user?.id === comment.author?.id ? (
kondisianalnya salah. namanya kan reply. kenapa ini comment.author?

2023-05-29 05:50 UTC, beruangdev commented on packages/web/src/components/Form/CommentForm.tsx
> +                    auth?.user?.id === comment.author?.id ? (
ini punya component comment, aku lupa commit untuk comment form, jadi terikut di commit review

2023-05-29 07:14 UTC, karyanayandi commented on packages/web/src/components/Form/CommentForm.tsx
> +                    auth?.user?.id === comment.author?.id ? (
tolong difix. sekalian sama tampilan bila user ngga login

2023-05-30 04:56 UTC, beruangdev commented on packages/web/src/components/Form/CommentForm.tsx
> +                    auth?.user?.id === comment.author?.id ? (
Okeee yan

2023-06-05 08:18 UTC, merged